import tkinter as tk
buttonFrame = tk.Frame(root)
buttonFrame.columnconfigure(0, weight=1)
buttonFrame.columnconfigure(1, weight=1)
buttonFrame.columnconfigure(2, weight=1)
buttonFrame.columnconfigure(3, weight=1)
btn1 = tk.Button(buttonFrame, text="1", font=("Arial", 18))
btn1.grid(row=0, column=0, sticky="we")
btn2 = tk.Button(buttonFrame, text="2", font=("Arial", 18))
btn2.grid(row=0, column=1, sticky="we")
btn3 = tk.Button(buttonFrame, text="3", font=("Arial", 18))
btn3.grid(row=0, column=2, sticky="we")
btnminus = tk.Button(buttonFrame, text="-", font=("Arial", 18))
btnminus.grid(row=0, column=3, sticky="we")
btn4 = tk.Button(buttonFrame, text="4", font=("Arial", 18))
btn4.grid(row=1, column=0, sticky="we")
btn5 = tk.Button(buttonFrame, text="5", font=("Arial", 18))
btn5.grid(row=1, column=1, sticky="we")
btn6 = tk.Button(buttonFrame, text="6", font=("Arial", 18))
btn6.grid(row=1, column=2, sticky="we")
buttonFrame.pack(fill="x")